# Generated by Django 4.2 on 2023-05-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchevsto', models.CharField(max_length=50, verbose_name='Отчевство')),
                ('date_and_time', models.DateTimeField(verbose_name='Дата посещения')),
                ('service', models.CharField(max_length=50, verbose_name='Услуга')),
            ],
        ),
    ]
