# Generated by Django 4.2 on 2023-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otchevsto', models.CharField(max_length=50, verbose_name='Отчевство')),
                ('data_birth', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
    ]
