# Generated by Django 4.2 on 2023-05-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_clients_alter_bank_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='otchevsto',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='otchevsto',
        ),
    ]
