# Generated by Django 4.2 on 2023-05-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sotrudnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='sotrudnik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sotrudnik'),
        ),
        migrations.CreateModel(
            name='Dolzhnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Должность')),
                ('sotrudnik', models.ManyToManyField(to='main.sotrudnik')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(verbose_name='Сумма')),
                ('procent', models.IntegerField(verbose_name='Процент')),
                ('years', models.IntegerField(verbose_name='Лет')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
            options={
                'verbose_name': 'Кредит',
                'verbose_name_plural': 'Кредиты',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.IntegerField(verbose_name='Сумма')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.clients')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
    ]
