# Generated by Django 4.2 on 2023-05-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bank_sotrudnik_dolzhnost_credit_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dolzhnost',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
